### PR TITLE
OCF tool

### PR DESCRIPTION
**Pull request by lgsmith**
This is a draft of the Orientational Correlation Function tool I wrote. I would really love it if someone would play with this one a bit, but I think it is working correctly on a test system. The test system was a bit pathological, so if someone has a longer simulation of an unstructured chain that would be helpful.

### CODE REVIEW

**Review by agrossfield — CHANGES_REQUESTED** [review]
- Please revert the change to Packages/User/SConscript (there should be a trailing space)
- Remove the incorrect change to xy_rdf.cpp -- you fixed this in your weights pull request, but somehow it's still here.
- Is there a reason you created uvdot? Why not just use multiply? x
 Even if you're going to define it, the implementation is unnecessarily obscure -- the function could literally be written in one line as a*b/(a.length() * b.length());
- remove testconfig.ini 

In the ocf tool itself:
- You've got a pretty major block of nearly identical code repeated 5 times in the main executable -- the loop over frames. Why is it inside the if's? Usually, we'd have a bunch of if's setting up exactly how the calculation would work, then have the loop over frames. If it's subtly different, could you refactor that loop into its own function? I haven't studied it carefully yet, but I can't escape the thought that there's got to be a better way to structure it so it's not repeated.

**Comment by lgsmith** [comment]
On uvdot: it's written the way it is because it exactly mimics the definition of the dot-product, in that same source file. It seems like a fundamental low-level math concept so I thought I'd just write it the same way.

On the other things: I do not know why merges from main are not overriding these changes. Input would be helpful. Also what is wrong with xy_rdf.cpp?

On the tool: The repetitive code is an alternative to using function pointers, or `std::variant`. This is what I've been talking about for a while now, where we have a fundamental problem with tools that have alternative functionality that is hard to solve without 1) a class hierarchy, which takes a while and doesn't make sense from my perspective 2) if-else networks inside of the loop, which is slightly less voluminous but still not great, and also bad practice, 3) function pointers, or 4) `std::variant` and `std::visit` approaches that use functions or functors. I probably would do 4 in the future, but I've never done it before and don't want to burn more time on this tool. Also I've been told not to use 'functional' solutions before, whereas this situation seems to call for them. What do you propose I do?

**Comment by agrossfield** [comment]
I would replace uvdot with the shorter version -- there's no reason to have the code repeated, and the other way will make it immediately obvious what you're doing. 

I'm guessing you branched this from main a while ago -- `git merge main` should (hopefully) fix it.

The xy_rdf change was a mistake where you'd globablly changed "weights" to "pweights" and you'd accidentally changed the option name as well.

**Comment by lgsmith** [comment]
No I merged with main again last night...

**Comment by agrossfield** [comment]
As for the functional stuff, unless I'm missing something the block from lines 272-282 is repeated verbatim at the end of every possible branch of the list of ifs -- why not just pull it out to the end? Why does it need to be in the if block at all?

**Comment by lgsmith** [comment]
Because then it's not in the loop anymore. Either the ifs have to be in the loop or you have to do one of the other things I suggested. 

I could write a second set of identical if-statements where the divergent setup is done before entering the if block surrounding the trajectory loop, but that seemed ridiculous too. It would reduce the repetitiveness of the code in the sense that there would be fewer lines initializing vectors within each if-block the second time, though.

**Comment by agrossfield** [comment]
But the repeated stuff comes _after_ all of that stuff. You have the same function calls, with the same variable names, so at the bare minimum that block can be replaced with a function call. Moreover, the block is the *last* thing in each if-block -- unless I'm missing something, nothing specific to the if-block takes place during or after the loop over trajectory.

So, you program would look like:

```
// set up which groups of atoms I'm looking at 
if ( ) {
} else if { }

...
// Now that I've set everything up -- loop over the trajectory and do the calculation
for (auto frame_index : mtopts->frameList()) {
￼        traj->readFrame(frame_index);
￼        traj->updateGroupCoords(scope);
￼        // get frame weights; defaults to zero
￼        const double weight = weights->get();
￼        weights->accumulate();
￼        com_bond_vectors(chain, bond_vectors);
￼        compute_ocf_bondlength(max_offset, bond_vectors, accum_ocf, mean_ocfs,
￼                               var_ocfs, accum_sq_mean, weight, bondlength);
￼      }
￼bondlength /= bond_vectors.size() * mtopts->frameList().size();

// Write the output
```

What am I missing?

**Comment by lgsmith** [comment]
the line containing `com_bond_vectors(...)` must be within the loop as they need to be recalculated at each `traj->updateGroupCoords()`, and it is a function of which `ifs` are triggered. The `bond_vectors` it produces are then used in the same fashion by all the loops. This is why you can't separate which loop is chosen from what is done within the loops without a function pointer picking between the various bond-vector update functions that are at the top of the tool. If one were to do that, then the traj-loop would only exist in one place.

**Comment by agrossfield** [comment]
The 3 possible functions differ by 1 line (and they could collapse to 2 cases, if you chose to represent the single atom case as a `vector<AtomicGroup>` where each group had one atom, which would make the centroid() call a no-op). 

Right now, it's really not obvious that all of the if cases are identical except for how you pick out the centers, which I'd argue is the most important part. Putting the update in an if/else inside the loop over trajectories would be shorter and clearer. If you *really* want to, you could use a function pointer, but honestly if/else makes more sense without even breaking them as functions, since the functions are so short.

**Comment by lgsmith** [comment]
Are you saying what the ifs are doing is not obvious because of inadequate commenting? Moving them inside the trajectory loop will reduce performance, but I'm wondering why (without additional comments) you think it will make things clearer. 

To me, function names and comments explain the purpose or behavior of a block of code, so eliding these landmarks will reduce clarity, not increase it.

**Comment by agrossfield** [comment]
The problem is that right now, the structure of the program makes it look like there are 5 cases that are totally different from each other, when in reality, there are 5 ways to pick out which sites to use, after which the procedure is identical (other than centroid vs centerOfMass). I would argue that emphasizing the similarity is by far the most important thing -- right now, someone scanning the code to understand what ocf is will have a hard time figuring it out, since they won't know they can safely check only one of the if branches to figure it out.

Truth is, you don't actually need any extra cases in the loop one trajectory -- you could set the up the single atom case to be single atom AGs, and you could collapse centroid() into centerOfMass() by manually setting the masses to 1 during the setup if they ask for centroid, and then just always call centerOfMass() in the main loop. I doubt the performance hit would even be measurable. However, if you don't want to do that, you can use a functor to customize the one thing that varies in the loop over frames.

**Comment by agrossfield** [comment]
The updated version with the function pointer is much better. The last thing I'd ask is that you comment it when you create it -- right before line 255, add something like

// Define pointer to the function that will update the bond sites -- will be either com_bond_vectors or centroid_bond_vectors, 
// depending on user input

**Comment by lgsmith** [comment]
I added a function pointer set up to get rid of the repetitive code.

**Comment by lgsmith** [comment]
OK I've added that comment.

**Pull request merged**
