### PR TITLE
Hard contacts

### PR DESCRIPTION
**Pull request by Poruthoor**
Added  two versions of hardContacts() function : One where the distance calculated between centroids is 3D Euclidean distance where for other it is 2D Euclidean distance. Useful if someone wants to find specific AG neighbors around a given AG selection within a cutoff radius. Also, useful if one wants to calculate local density of one AG around another within a cutoff radius.

Added 2D version of logisticContacts() earlier added by @agrossfield.

### CODE REVIEW

**Comment by agrossfield** [comment]
2 suggestions:

1. A better way to zero out the z-components of a GCoord (e.g. line 246) is to just say 
`centroid.z() = 0.;`
or 
`centroid.z(0.);` 
(only the latter works in python, but the former is the most expressive, I think)

2. Right now, the 3D and 2D versions of logisticContact have a ton of code duplication. I suggest pulling the repeated part (lines 249-269) into a separate function, then calling that function from both methods. The function should be marked private, because it's not part of the API.

**Comment by agrossfield** [comment]
Naming convention: the methods should be logisticContact2D and hardContact2D, without the underscore

**Comment by Poruthoor** [comment]
- [x] Zero outing the z component done in an expressive way
- [x] Naming conventions are followed
- [x] Code duplication is reduced by introducing a private function

**Review by agrossfield — APPROVED** [review]
WIth these revisions, it looks good.

**Pull request merged**
