### PR TITLE
Implement Mdtraj-hdf5 format

### PR DESCRIPTION
**Pull request by agrossfield**
---
name: Pull request
about: support hdf5 format
title: ''
labels: ''
assignees: ''
---

## Changes proposed in this pull request
    - Add new classes MDTraj and MDTrajTraj to read MDTraj hdf5 files as a system file and trajectory respectively

## Checklist
    - Does this pull request address an open issue? If so, which one?

No

    - Have you applied a formatter to your code (e.g. flake8 or black for python, clang-format for C++)?

Yes

### CODE REVIEW

**Comment by agrossfield** [comment]
There are a couple of test programs in  Packages/User that will need to be removed before the final merge. I'm leaving them for now in case more testing is needed

**Comment by agrossfield** [comment]
One other thing that will need to be done is adding hdf5 as a dependency in the conda-forge recipe.

**Comment by tromo** [comment]
Looks good for small values of looking...

**Review by tromo — APPROVED** [review]
Looks good.

**Pull request merged**
