### PR TITLE
Long bond finder and python uplift 

### PR DESCRIPTION
**Pull request by lgsmith**
---
name: Pull request
about: Create a report to incorporate code
title: 'Look for periodicity issues by finding overlong bonds'
labels: 'cli-tools, traj-processing, imaging-issue-check'
assignees: 'agrossfield'
---

Fixes no issue

## Changes proposed in this pull request
    - wrote tool to efficiently search for overlong bonds in trajectories
    - added key methods to atomic group for use in pythonic contexts
    - changed python typelifting of AG iterators to be concise and efficient (call `list()` instead of for-loop-append idiom).

## Checklist
    - Does this pull request address an open issue? If so, which one?
        - No
    - Have you applied a formatter to your code (e.g. flake8 or black for python, clang-format for C++)?
        - Yes

### CODE REVIEW

**Review by agrossfield — CHANGES_REQUESTED** [review]
I'm a little concerned by unordered_pair_hash -- does XOR'ing 2 hashes produce something unique? Perhaps I'm mistaken, but it seems like collisions are very possible.

An alternative would be to do something like:

- sort pair.first and pair.second so they're in a consistent order
- make a string out of "first:second" or something like that
- hash that (or use it as a key for a map and replace the unordered set) 

I'd suggest something like hash(larger*num_bonds + smaller), which is guaranteed to be unique, but I don't see an obvious way to get num_bonds into the needed functions unless you store the number of bonds in the AG (which would be fine, too).

However, it's not clear to me why you have the bond_set stage at all -- unless I'm missing something, you build up the bond_set as a local variable, copy its contents into bond_list, and return bond_list. Is there a reason not to just put them straight into the bond_list?

In `AtomicGroup::groupFromID`, the null checks in lines 638 and 641 are pointless as written, since you don't throw an error. If one of the checks fails, you'll return an AG with one atom, which will presumably break stuff downstream. To my mind, this should clearly throw. However, I know @tromo is revising the way we do error reporting preparatory to the next release (this will make us compatible with the newest compilers), so we should get his comments before you make changes.

**Comment by agrossfield** [comment]
Another thought: it might be worth mentioning in the fullhelp that `merge-traj` with the `--fix-imaging` flag should be able to fix the problems found by this program; see the [wiki on working with gromacs](https://github.com/GrossfieldLab/loos/wiki/Preparing-to-analyze-a-gromacs-simulation). I know that's too labor-intensive for your use-case, but for people running conventional dynamics simulations there's way to never see the problem (other than just not using gromacs :-) ).

**Comment by lgsmith** [comment]
So I think that for the way this code uses the find-bonds functionality, there'd be no way that it would not find the atoms. For other use cases, I can see why having one defined but not the other would be an error, but I think returning an empty AG is actually OK. Still in a holding pattern there, but I think everything else has been resolved.

**Review by agrossfield — COMMENTED** [review]
I see another relatively small problem. As it stands, you run model.findBonds() to identify bonds in the absence of connectivity without checking model.hasCoords() first. Since two of the most commonly used model file formats (Amber prmtop and NAMD psf) don't have coordinates I think you should at a minimum check for coordinates.  IIRC, all coordinates are 0,0,0 when not set, so you'd quite hilariously conclude that everything is bonded to everything else.

So, the simplest solution is just to add a hasCoords() check around line 237 and throw if it's not set. A slightly better solution would be to use the first frame of the trajectory in that case, which would require a little bit of reorganization.

**Review by agrossfield — COMMENTED** [review]
Another truly tiny request: when writing the timeseries (including the header), I personally prefer tabs to spaces as delimiters, because looks neater. Feel free to ignore me if you think this is too much.

**Comment by lgsmith** [comment]
> I see another relatively small problem. As it stands, you run model.findBonds() to identify bonds in the absence of connectivity without checking model.hasCoords() first. Since two of the most commonly used model file formats (Amber prmtop and NAMD psf) don't have coordinates I think you should at a minimum check for coordinates. IIRC, all coordinates are 0,0,0 when not set, so you'd quite hilariously conclude that everything is bonded to everything else.
> 
> So, the simplest solution is just to add a hasCoords() check around line 237 and throw if it's not set. A slightly better solution would be to use the first frame of the trajectory in that case, which would require a little bit of reorganization.

I thought about this, and what I concluded was that there is no format that both lacks chemical connectivity and also coordinates. So prmtops and psfs should run just fine with this code, because they have connectivity LOOS can understand unless they are malformed. PDBs should also work as long as you use `--infer-connectivity`, or the PDB has connect records. The only situation I can think of where this would actually occur would be one where you've used some other program to write a PDB, but you wrote it from a format with no crds (so that every atom's position was (0, 0, 0)), and you also instructed that other program not to write connect records into said PDB. This seems pathological enough that we shouldn't have to check for it (what would a pdb with no coords and no connect records have in it??? A list of the atoms present in each molecule, I suppose, but with no other information about them why even have such a file?) but if you want me to include the check regardless I can.

**Review by agrossfield — APPROVED** [review]
All of this looks good.

**Review by agrossfield — APPROVED** [review]

**Pull request merged**
