### PR TITLE
Gitignore upgrade

### PR DESCRIPTION
**Pull request by lgsmith**
This uses the fact that new executables should reside within source-containing directories to ignore the contents of those directories, minus a few exception patterns. Leaves 'already tracked' files that would be excluded without a `git add -f` already tracked (for example, the contents of `Packages/OptimalMembraneGenerator/example` would be ignored without a specific add, but because those files are currently tracked any adjustments to them will be tracked as well. If someone were to rename one not using `git mv` or were to add a new file to that directory, it would be ignored. This actually seems fine to me, because I think that in general a user probably doesn't want to accidentally add *.inp files that are floating around the loos directory tree, but this could be changed too if needed. 

Also, builds!

### CODE REVIEW

**Review by agrossfield — COMMENTED** [review]
This looks great, and seems to behave correctly on my tree.

More a comment than a complaint: I'm confused by the block from line 81-84 -- it seems like those lines are partly canceling each other. Could you expand the comment explaining why?

Also, can you put a comment at the top of the file suggesting what the convention should be for naming new README's, etc, should be -- e.g. "going forward, use the name 'README.md' to ensure that this file doesn't block it. I'm trying to think where else such a comment should go, but there's no obvious spot.

**Comment by agrossfield** [comment]
One other thing: you can remove the line about .gitignore-prev -- that was created for my hack, which you've nicely superceded.

**Comment by lgsmith** [comment]
Ah so the thing that is confusing about .gitignores and git directory tracking is that it seems bashlike but is not. If one issues a command in the gitignore that would match a directory name, that directory is ignored _and its contents are therefore not indexed_. The manpage says this is for 'performance reasons'.\* So you need to explicitly tell git 'ignore the contents of this directory, but do not ignore the directory itself' for ignore-negation patterns to be applied to the contents of the directory. This is the issue I figured you ran into when you tried naive globbing and then wrote your python script instead. 

Thus, by saying `src/*` I'm telling git, "ignore everything in src, but not src, so you still need to index src's contents." This will then cause the other things I've told git, in this case `!**.cpp` and `!**.hpp`, which can be translated to "don't ignore matches ending in '.cpp' or '.hpp' regardless of their prefix path" to be applied to the indexed contents, which means that if you add a new C++ source to that directory and use the `.cpp` extension, it'll get indexed and therefore tracked. Conversely, the instruction `*` would expand to ignoring the `src/` directory, which means its contents would not be indexed, which means the aforementioned exceptions would not be applied. The bummer here is that because `Packages` has depth, its subdirectories will be ignored by the `Packages/*` directive, which is why I used the pattern `!Packages/*/`, then `Packages/*/*`. It amounts to saying 'ignore the contents of the contents of packages, but do index directory and subdirectory contents.

This last part is why I made the remark about the `Packages/OptimalMembraneGenerator/example` directory in my first comment. The _subdirectories_ of `example` are being tracked only because their content has been tracked previously, so if someone were to add a new file git had not previously tracked, or change the directory structure there (without using `git mv` to do so) the gitignore patterns would cause those files to be ignored when that person then ran `git add .` in that directory. If they follow the suggestions in the gitignore comment they'd find this out by running `git check-ignore -v newfile_that_is_being_ignored`. They could either use `git add -f newfile_that_is_being_ignored`\*\* or add another layer of indexing to the gitignore to change this. Note that we use this nonconformity with the general gitignore in several other places (so far as I've noticed, with some of the source files for flex-bison in `src/` and `Packages/User/README`) so this seemed OK to me, but I think you can see how to add further depth to git's indexing of the `Packages/` tree given what I've written here.

For what it's worth, I felt that your confusion on this issue was partly due to poor wording in my comment, so I've added a much more significant comment to lines 73-77 that hopefully distills this overlong post into actionable instructions for future users. To remove temptation to apply the `update_gitignore.py`, which is now no longer needed, I also git-rmed that. I can revert that, if you think this last choice is an issue.

\*I'm not a fan, because this means that although file-level ignores need not be manually maintained if good pattern matching on files can be done instead, effectively the directory structure _does_. I'm sure that some linux-beards would have some wiseacre remark about how this so-called performance is needed for some crazy use-case they've found, but I'm going to guess that's an 0.01 percentile application of git and this should be at the very least an alternative behavior one could ask for in their gitconfig, given how unintuitive it is for those that think they know what `*` means. If this is possible and I'm complaining about nothing I'd be thrilled to hear that, but I've found no evidence that it is adjustable in my googling.

\*\*It occurred to me while doing all of this that if one were starting a fresh bare repo then one could have a gitignore looking like '*' with no other content and just manually add all important files as one wrote them. This wouldn't be very hard, because anyone trying to make a change would frustratedly notice that they couldn't add it, then read the readme or other docs saying, 'you need to use `git add -f filename` if you want to add _anything_'. It actually wouldn't be too terrible to do this with loos either, because all the files we want to track in this 'explicit' mode are already tracked (try changing your gitignore to a single glob--it doesn't drop already tracked files) but it is more unorthodox than just letting a person run `git add .` from wherever and having the gitignore figure stuff out for itself.

**Comment by lgsmith** [comment]
Oh also, I didn't create a pattern for 'readme's or anything of the sort. It makes sense to me to use markdown format, because that gives an extension to track and means that people who don't want to read rawtext, or people who want math-rendering in their readme, can both have their cake. It just seemed like a separate issue to me. Happy to add those features to the ignore as well, though they'd also need to be added to the docs or wiki somewhere, which is work that I'm not as close to.

**Comment by agrossfield** [comment]
Thanks for including the detailed explanation -- having it here will make it accessible if/when something needs to change in the future.

**Pull request merged**
