### PR TITLE
Weights default

### PR DESCRIPTION
**Pull request by lgsmith**
Default behavior to let weights-options just initialize a bunch of weights of 1.0 to eliminate need for branched code that uses weights.

### CODE REVIEW

**Comment by agrossfield** [comment]
A couple of preliminary things that need to change:

- Need to delete extraneous files (Packages/Clustering/Makefile and an ini file)
- Some code breaks loos naming conventions ( get_weights should be getWeights). The original code also broke this rule, but we might as well clean it all up at once

The bigger change is that I think we should have a virtual parent class Weights, and then UniformWeights and the current Weights class (perhaps renamed as WeightsFromFile or something like that) as subclasses of it. As we've discussed, this would leave it open for other ways of getting weights (eg somehow computing them on the fly or iteratively).

**Comment by lgsmith** [comment]
I've updated and reorganized the weights classes so that they form a hierarchy specifying an interface. This should be something we can extend as needed--if it seems like, after review, there's some major obstacle to that then let me know.

I did a basic test with rdf to see if it works. It'd be nice if someone who has a weights/simulation combination that they have expected results for, could test rdf or xy_rdf, both with and without the weights.

**Comment by agrossfield** [comment]
@tromo : could you take a look at this? His basic strategy looks ok to me, but you're more sophisticated with some of these techniques.

**Comment by lgsmith** [comment]
OK, after these updates there should be no further issues with building on mac. I also changed the method names as requested.

**Review by agrossfield — COMMENTED** [review]
Line 111 of xy_rdf.cpp -- you changed the command line option check from weights to pweights, but the command line option should still be "weights" I think

**Review by agrossfield — CHANGES_REQUESTED** [review]
somehow the binary Packages/User/noes has shown up again

**Comment by lgsmith** [comment]
These edits should have rectified the `noes` binary inclusion and the issue with the failed find-replace in `xy_rdf.cpp`. Let me know if any further issues arise, but I believe that this should be ready for merging.

**Pull request merged**
