### PR TITLE
ESP mesh tool

### PR DESCRIPTION
**Pull request by chapincavender**
This PR adds a tool called esp_mesh to fit charges on a mesh composed of spherical shells to reproduce the electrostatic potential due to solvent around a solute. The new tool is in Tools/. The change to src/loos_defs.hpp declares an additional LAPACK routine, dgels, that I needed to fit the charge magnitudes by linear regression.

### CODE REVIEW

**Comment by agrossfield** [comment]
This looks like it'll be very easy to incorporate.  A couple of suggestions/questions, first:
1. In the fullhelp message, explain the default selections. The one for the solvent atoms appears to be residues that are named WAT or residues containing a + or - in the names. That may work for Amber naming, but won't work for other force fields, which is fine, but folks need to know that. 
2. Am I correct in reading that anything not selected as solvent is implicitly used as the solute?
3. When you computed the electrostatic potential, you calculate the distance without periodicity, unless I'm missing something. I assume this is because you assume the solute has been centered at the origin. This should be documented in the fullhelp, because it's a pretty major gotcha.
4. The fullhelp should specify the units for outputting the electrostatic potential.

**Comment by chapincavender** [comment]
Thanks for your comments! These should be easy fixes.

> Am I correct in reading that anything not selected as solvent is implicitly used as the solute?
The default selection strings for solute and solvent are set up this way, but the two selections don't have to be exactly complementary. For example, if you want to draw the mesh around part of a large solute molecule but only use the traditional solvent to build the mesh, there could be atoms that are part of neither selection.

> you calculate the distance without periodicity
Yes, that's right. My thoughts are that if you need to use periodic distance here then your box is too small. But I will document this in the fullhelp.

**Comment by agrossfield** [comment]
The only reason I was worried about periodicity is because you don't explicitly tell people they need to put the solute at the origin. As long as you document that in the fullhelp (perhaps in a section labelled "GOTCHAS"), or in some kind of easy-to-see place elsewhere, I think you're fine. However, that's the most obvious mistake someone could make using your program, so we need to warn them.

Would it be hard for you to auto-center (or even align) the solute for them? I can't see why not.

**Comment by chapincavender** [comment]
> Would it be hard for you to auto-center (or even align) the solute for them? I can't see why not.

It wouldn't be hard, but then the coordinates of the mesh in the output will be shifted from the trajectory. So I think we would need to output a PDB containing the new solute coordinates.

Also, this behavior would break for systems with periodic boxes that are not triclinic, so we need to either make it an optional flag or provide a flag to turn it off.

**Comment by agrossfield** [comment]
In that case, I’d sat table it for now. We can always add the option later. I’m thinking after the release my next big project will be to add support for truncated octahedral boxes.

**Comment by agrossfield** [comment]
Merged electrostatic mesh tool from Chapin Cavender

**Pull request merged**
